registory: 964246069091.dkr.ecr.us-east-1.amazonaws.com
images:
  simulator:
    repository: simulator
    tag: 6feb4e026009dbfcc94f7a0c6110a28e6f4643df
  bridge:
    repository: bridge
    tag: 6feb4e026009dbfcc94f7a0c6110a28e6f4643df
  linetrace_control:
    repository: linetrace_control
    tag: d9abbe52ae00cbb19897da6ce4a5296c1bc355b8
  teleop_key:
    repository: teleop_key
    tag: d190fb722daf6c1b61cee2013f7edf207eaee1a9
