registory: 964246069091.dkr.ecr.us-east-1.amazonaws.com
images:
  simulator:
    repository: simulator
    tag: 0ffe497d6af3f90bece0e83915b483c5918b89d9
  bridge:
    repository: bridge
    tag: 0ffe497d6af3f90bece0e83915b483c5918b89d9
  linetrace_control:
    repository: linetrace_control
    tag: d45b8ccb39c7a82b6dcf2dbaa94b5647ad765541
  teleop_key:
    repository: teleop_key
    tag: d45b8ccb39c7a82b6dcf2dbaa94b5647ad765541
